//
//  main.m
//  cd to ...
//
//  Created by James Tuley on 2/16/07.
//  Improvements by Yang Zhang, 2016.
//  Copyright Jay Tuley 2007. All rights reserved.
//

#import <Cocoa/Cocoa.h>

#import "CD2Protocol.h"
#import "CD2ITerm.h"
#import "CD2Terminal.h"

// Finder.h Generated by: sdef /System/Library/CoreServices/Finder.app | sdp -fh --basename Finder
#import "Finder.h"

NSString* getPathToFrontFinderWindow() {
    FinderApplication* finder = [SBApplication applicationWithBundleIdentifier:@"com.apple.Finder"];
    FinderItem *target = [[[finder selection] get] firstObject];
    if (target == nil) {
        target = [[[[finder FinderWindows] firstObject] target] get];
    }
    NSURL* url = [NSURL URLWithString:target.URL];
    NSData* bookmark = [NSURL bookmarkDataWithContentsOfURL:url error:nil];
    NSError* error;
    NSURL* fullUrl = [NSURL URLByResolvingBookmarkData:bookmark
                                               options:NSURLBookmarkResolutionWithoutUI
                                         relativeToURL:nil
                                   bookmarkDataIsStale:nil
                                                 error:&error];
    if (fullUrl != nil) {
        url = fullUrl;
    }
    NSString* path = [[url path] stringByExpandingTildeInPath];

    BOOL isDir = NO;
    [[NSFileManager defaultManager] fileExistsAtPath:path isDirectory:&isDir];

    if (!isDir) {
        path = [path stringByDeletingLastPathComponent];
    }

    return path;
}

void sendNotification(NSString* msg) {
    NSUserNotification *note = [NSUserNotification new];
    note.title = @"cd to ...";
    note.informativeText = msg;
    [[NSUserNotificationCenter defaultUserNotificationCenter] deliverNotification:note];
}

int main(int argc, char *argv[]) {
    id pool = [[NSAutoreleasePool alloc] init];
    
    NSString* path;
    @try {
        path = getPathToFrontFinderWindow();
    } @catch (id ex) {
        path = nil;
    }

    NSLog(@"FINDER PATH = %@", path);

    if (path == nil) {
        sendNotification(@"Finder window not found, or is not a valid path!");
    } else {
        // Try iterm first
        CD2ITerm* iterm = [[[CD2ITerm alloc] init] autorelease];
        if (![iterm openTermWindowForPath:path]) {
            NSLog(@"Failed to open iTerm window");
            // iTerm failed to open, try system Terminal
            CD2Terminal* term = [[[CD2Terminal alloc] init] autorelease];
            if (![term openTermWindowForPath:path]) {
                NSLog(@"Failed to open Terminal window");
                // system Terminal also failed, send error message to Notification Center
                sendNotification(@"Failed to open iTerm/Terminal window!");
            }
        }
    }

    [pool release];
    return 0;
}
